/* eslint-disable no-unused-vars */
const exbrowser = "chrome";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.stefanvd.net/project/zoom/browser/options/";
const linkdeveloperwebsite = "https://www.stefanvd.net";
const linkproduct = "https://chromewebstore.google.com/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd";
const linkdonate = "https://www.stefanvd.net/donate/";
const writereview = "https://chromewebstore.google.com/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd/reviews";
const linkchangelog = "https://www.stefanvd.net/project/zoom/browser/google-chrome/changelog/";
const linktranslate = "https://www.stefanvd.net/project/translate/";
const linksupport = "https://www.stefanvd.net/support/";
const linkwelcome = "https://www.stefanvd.net/project/zoom/browser/google-chrome/welcome/";
const linkuninstall = "https://www.stefanvd.net/project/zoom/browser/google-chrome/uninstall/";
const linkguide = "https://www.stefanvd.net/project/zoom/browser/google-chrome/guide/";
const linkproductdescription = "https://www.stefanvd.net/project/zoom/browser-extension/";
const browsernewtab = "chrome://newtab/";
const browserstore = "https://chromewebstore.google.com";
const linkyoutube = "https://www.youtube.com/@stefanvandamme?sub_confirmation=1";
const devmode = true;
const devdonate = false;