/* eslint-disable no-unused-vars */
const exbrowser = "opera";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.stefanvd.net/project/print/browser/options/";
const linkdeveloperwebsite = "https://www.stefanvd.net";
const linkproduct = "https://addons.opera.com/extensions/details/print/";
const linkdonate = "https://www.stefanvd.net/donate/";
const writereview = "https://addons.opera.com/extensions/details/print/";
const linkchangelog = "https://www.stefanvd.net/project/print/browser/opera/changelog/";
const linktranslate = "https://www.stefanvd.net/project/translate/";
const linksupport = "https://www.stefanvd.net/support/";
const linkwelcome = "https://www.stefanvd.net/project/print/browser/opera/welcome/";
const linkuninstall = "https://www.stefanvd.net/project/print/browser/opera/uninstall/";
const linkguide = "https://www.stefanvd.net/project/print/browser/opera/guide/";
const linkproductdescription = "https://www.stefanvd.net/project/print/browser/";
const browsernewtab = "opera://newtab/";
const browserstore = "https://addons.opera.com";
const linkyoutube = "https://www.youtube.com/@stefanvandamme?sub_confirmation=1";
const devmode = true;
const devdonate = false;