/* eslint-disable no-unused-vars */
const exbrowser = "firefox";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.stefanvd.net/project/proper-menubar/browser/options/";
const linkdeveloperwebsite = "https://www.stefanvd.net";
const linkproduct = "https://addons.mozilla.org/en-US/firefox/addon/proper-menubar/";
const linkdonate = "https://www.stefanvd.net/donate/";
const writereview = "https://addons.mozilla.org/en-US/firefox/addon/proper-menubar/reviews";
const linkchangelog = "https://www.stefanvd.net/project/proper-menubar/browser/firefox/changelog/";
const linktranslate = "https://www.stefanvd.net/project/translate/";
const linksupport = "https://www.stefanvd.net/support/";
const linkwelcome = "https://www.stefanvd.net/project/proper-menubar/browser/firefox/welcome/";
const linkuninstall = "https://www.stefanvd.net/project/proper-menubar/browser/firefox/uninstall/";
const linkguide = "https://www.stefanvd.net/project/proper-menubar/browser/firefox/guide/";
const linkproductdescription = "https://www.stefanvd.net/project/proper-menubar/browser/";
const browsernewtab = "about:blank";
const browserstore = "https://addons.mozilla.org";
const linkyoutube = "https://www.youtube.com/@stefanvandamme?sub_confirmation=1";
const devmode = true;
const devdonate = false;

const browserextensions = "about:addons";
const browsersettings = "about:preferences";
const browserdownloads = "about:downloads";
const browserpolicy = "about:policies";
const browserinspect = "about:devtools";
const browserflags = "about:config";
const browserabout = "about:support";
const browserbookmarks = "https://getpocket.com/a/queue";
const browserhistory = "https://myactivity.google.com/myactivity";