/* eslint-disable no-unused-vars */
const exbrowser = "firefox";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.stefanvd.net/project/font-size-increase/browser/options/";
const linkdeveloperwebsite = "https://www.stefanvd.net";
const linkproduct = "https://addons.mozilla.org/en-US/firefox/addon/font-size-increase-for-firefox/";
const linkdonate = "https://www.stefanvd.net/donate/";
const writereview = "https://addons.mozilla.org/en-US/firefox/addon/font-size-increase-for-firefox/reviews";
const linkchangelog = "https://www.stefanvd.net/project/font-size-increase/browser/firefox/changelog/";
const linktranslate = "https://www.stefanvd.net/project/translate/";
const linksupport = "https://www.stefanvd.net/support/";
const linkwelcome = "https://www.stefanvd.net/project/font-size-increase/browser/firefox/welcome/";
const linkuninstall = "https://www.stefanvd.net/project/font-size-increase/browser/firefox/uninstall/";
const linkguide = "https://www.stefanvd.net/project/font-size-increase/browser/firefox/guide/";
const linkproductdescription = "https://www.stefanvd.net/project/font-size-increase/browser/";
const browsernewtab = "null";
const browserstore = "https://addons.mozilla.org";
const linkyoutube = "https://www.youtube.com/@stefanvandamme?sub_confirmation=1";
const devmode = true;
const devdonate = false;