/* eslint-disable no-unused-vars */
const exbrowser = "chrome";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.stefanvd.net/project/zoom/browser/options/";
const linkdeveloperwebsite = "https://www.stefanvd.net";
const linkproduct = "https://chrome.google.com/webstore/detail/zoom/lajondecmobodlejlcjllhojikagldgd";
const linkdonate = "https://www.stefanvd.net/donate/";
const writereview = "https://chrome.google.com/webstore/detail/zoom/lajondecmobodlejlcjllhojikagldgd/reviews";
const linkchangelog = "https://www.stefanvd.net/project/zoom/browser/google-chrome/changelog/";
const linktranslate = "https://www.stefanvd.net/project/translate/";
const linksupport = "https://www.stefanvd.net/support/";
const linkwelcome = "https://www.stefanvd.net/project/zoom/browser/google-chrome/welcome/";
const linkuninstall = "https://www.stefanvd.net/project/zoom/browser/google-chrome/uninstall/";
const linkguide = "https://www.stefanvd.net/project/zoom/browser/google-chrome/uninstall/";
const linkproductdescription = "https://www.stefanvd.net/project/zoom/browser/";
const browsernewtab = "chrome://newtab/";
const browserstore = "https://chrome.google.com";
const linkyoutube = "https://www.youtube.com/c/stefanvandamme?sub_confirmation=1";
const devmode = true;
const devdonate = false;