/* eslint-disable no-unused-vars */
const exbrowser = "safari";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.stefanvd.net/project/zoom/browser/options/";
const linkdeveloperwebsite = "https://www.stefanvd.net";
const linkproduct = "https://apps.apple.com/app/id1423085875";
const linkdonate = "https://www.stefanvd.net/donate/";
const writereview = "https://apps.apple.com/app/id1423085875?action=write-review";
const linkchangelog = "https://www.stefanvd.net/project/zoom/browser/safari/changelog/";
const linktranslate = "https://www.stefanvd.net/project/translate/";
const linksupport = "https://www.stefanvd.net/support/";
const linkwelcome = "https://www.stefanvd.net/project/zoom/browser/safari/welcome/";
const linkuninstall = "https://www.stefanvd.net/project/zoom/browser/safari/uninstall/";
const linkguide = "https://www.stefanvd.net/project/zoom/browser/safari/guide/";
const linkproductdescription = "https://www.stefanvd.net/project/zoom/browser-extension/";
const browsernewtab = "chrome://newtab/";
const browserstore = "https://test.apple.com";
const linkyoutube = "https://www.youtube.com/@stefanvandamme?sub_confirmation=1";
const devmode = false;
const devdonate = false;