/* eslint-disable no-unused-vars */
const exbrowser = "safari";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.stefanvd.net/project/proper-menubar/browser/options/";
const linkdeveloperwebsite = "https://www.stefanvd.net";
const linkproduct = "https://chromewebstore.google.com/detail/" + chrome.runtime.id;
const linkdonate = "https://www.stefanvd.net/donate/";
const writereview = "https://chromewebstore.google.com/detail/" + chrome.runtime.id + "/reviews";
const linkchangelog = "https://www.stefanvd.net/project/proper-menubar/browser/google-chrome/changelog/";
const linktranslate = "https://www.stefanvd.net/project/translate/";
const linksupport = "https://www.stefanvd.net/support/";
const linkwelcome = "https://www.stefanvd.net/project/proper-menubar/browser/google-chrome/welcome/";
const linkuninstall = "https://www.stefanvd.net/project/proper-menubar/browser/google-chrome/uninstall/";
const linkguide = "https://www.stefanvd.net/project/proper-menubar/browser/google-chrome/guide/";
const linkproductdescription = "https://www.stefanvd.net/project/proper-menubar/browser-extension/";
const browsernewtab = "chrome://newtab/";
const browserstore = "https://chrome.google.com";
const linkyoutube = "https://www.youtube.com/@stefanvandamme?sub_confirmation=1";
const devmode = true;
const devdonate = false;
const helpenablebookmark = "https://www.stefanvd.net/support/how-to-display-bookmarks-proper-menubar/";
const browserextensions = "chrome://extensions/";
const browsersettings = "chrome://settings/";
const browserdownloads = "chrome://downloads/";
const browserpolicy = "chrome://policy/";
const browserinspect = "chrome://inspect/";
const browserflags = "chrome://flags/";
const browserabout = "chrome://settings/help";
const browserbookmarks = "chrome://bookmarks/";
const browserhistory = "chrome://history/";